load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "table",
    hdrs = ["table.h", "type.h", "table_helpers.h", "sort_helpers.h"],
    visibility = ["//visibility:public"],
    deps = [
      "//generic:generic",
    ],
)